---
apiVersion: v1
kind: Service
metadata:
  name: pihole
  labels:
    app: pihole
spec:
  selector:
    app: pihole
  ports:
  - name: dns-tcp
    protocol: TCP
    port: 53
  - name: dns-udp
    protocol: UDP
    port: 53
  - name: web
    protocol: TCP
    port: 80
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web-ui
spec:
  selector:
    name: pihole
  ports:
  - name: web
    port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole-web-ui
spec:
  rules:
  - host: pihole.rahools.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pihole-web-ui
            port:
              number: 80