apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-mqtt
  name: mqtt
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-mqtt
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-mqtt
    spec:
      containers:
      - image: eclipse-mosquitto
        imagePullPolicy: Always
        name: mqtt
        ports:
        - containerPort: 1883
          hostPort: 1883
          name: mqtt
          protocol: TCP
        volumeMounts:
        - mountPath: /mosquitto/config
          name: config
        - mountPath: /mosquitto/data
          name: data
        - mountPath: /mosquitto/log
          name: log
      volumes:
      - hostPath:
          path: ./mqtt/config
          type: ""
        name: config
      - hostPath:
          path: ./mqtt/data
          type: ""
        name: data
      - hostPath:
          path: ./mqtt/log
          type: ""
        name: log
