---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: homeassistant-config-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/rahools/pvs/homeassistant/config"