---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homeassistant-config-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi