---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  labels:
    app: homeassistant
spec:
  selector:
    app: homeassistant
  ports:
  - name: web
    protocol: TCP
    port: 8123
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: homeassistant-web-ui
spec:
  selector:
    name: homeassistant
  ports:
  - name: web
    port: 80
    targetPort: 8123

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant-web-ui
spec:
  rules:
  - host: homeassistant.rahools.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homeassistant-web-ui
            port:
              number: 80