apiVersion: v1
kind: Service
metadata:
  name: radarr-service
spec:
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-radarr
  ports:
  - protocol: TCP
    port: 7878
    targetPort: 7878