api: https://api.cloudflare.com/client/v4/
logLevel: info
auth:
  scopedToken: <cf_token>
domains:
  - name: <url>
    type: A
    proxied: true
    create: true
    zoneId: <zone_id>

ipv4:
  - type: json
    url: https://api.ipify.org?format=json
    fields:
      - ip
      
ipv6:
  - type: json
    url: https://api6.ipify.org?format=json
    fields:
      - ip