apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-bazarr
  name: bazarr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-bazarr
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-bazarr
    spec:
      containers:
      - image: hotio/bazarr:latest
        imagePullPolicy: Always
        name: bazarr
        ports:
        - containerPort: 6767
          hostPort: 6767
          name: bazarr-http
          protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /cache
          name: cache
        - mountPath: /shows
          name: shows
        - mountPath: /movies
          name: movies
      volumes:
      - hostPath:
          path: /home/rahools/k3s-data/bazarr/bazarr/config
          type: ""
        name: config
      - hostPath:
          path: /home/rahools/k3s-data/bazarr/bazarr/cache
          type: ""
        name: cache
      - hostPath:
          path: /mnt/exthhd/jellyfin-data/shows
          type: ""
        name: shows
      - hostPath:
          path: /mnt/exthhd/jellyfin-data/movies
          type: ""
        name: movies
