apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-ddns
  name: ddns
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-ddns
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-ddns
    spec:
      containers:
      - image: joshava/cloudflare-ddns
        imagePullPolicy: Always
        name: ddns
        volumeMounts:
        - mountPath: /app/config.yaml
          name: ddns-config
      volumes:
      - hostPath:
          path: ./ddns/config.yaml
          type: ""
        name: ddns-config
